#!/usr/bin/env python
import structlog

class PrintLogger(object):
    def __init__(self, **cfg):
        self.cfg = cfg

    def msg(self, msg, *a, **kw):
        pref = self.cfg.get('prefix', 'test: ')
        print(' '.join((pref, msg, str(kw))))

log = structlog.wrap_logger(PrintLogger(prefix='my prefix'))
log.msg('hi', key='value')

