#!/usr/bin/env python
import structlog, time, functools
partial = functools.partial

def proc1(*a):
    ev_dict = a[2]
    ev_dict['our_timestamp'] = time.ctime()
    return ev_dict

def proc2(Logger, meth_name, ev_dict, **cfg):
    # Last processor must match Logger method sig:
    # we are the 'renderer', no ev_dict after us anyway:
    ev_dict.update(cfg)
    return '%(our_timestamp)s %(event)s [%(msg)s]' % ev_dict

class PrintLogger(object):
    def __init__(self, **cfg):
        self.cfg = cfg

    def msg(self, msg):
        pref = self.cfg.get('prefix', 'test: ')
        print(' '.join((pref, msg)))

pl = PrintLogger(prefix='my prefix')
proc2 = partial(proc2, msg='custom message')

# import time of 1000 application modules containing statements like:
log2 = structlog.get_logger('some', 'factory', 'args')
# until config any message goes to the default processors:
log2.msg('hi from the default logger')

# application ready to start, now configure logging:
# giving all modules with .get_logger the same processors:
structlog.configure( processors     = [proc1, proc2]
                   , logger_factory = lambda *args: pl
                   )
log2.msg('hi, now conifgured to our logger')

